#!/usr/bin/env bash
# Bootstrap the E2E Spree backend using @spree/cli.
#
# Steps:
#   1. `spree seed` — seed the default store, roles, countries.
#   2. `spree sample-data` — load sample products, categories, images.
#   3. `spree api-key create --name E2E --type publishable` — mint a key
#      and capture the printed pk_… token.
#
# Idempotent: the CLI's seed/sample-data tasks are no-ops on already-seeded
# databases, and a fresh API key per run is fine (old "E2E" keys just
# accumulate but don't break anything).
#
# Output: writes `.env.e2e` at the repo root with SPREE_API_URL +
# SPREE_PUBLISHABLE_KEY for the storefront to consume.

set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
readonly BACKEND_DIR="$REPO_ROOT/e2e-backend"
readonly ENV_FILE="$REPO_ROOT/.env.e2e"
readonly SPREE_URL="http://localhost:4000"

# Stripe's public sample publishable key — same one used throughout
# https://docs.stripe.com/keys and Stripe's own getting-started examples.
# Test-mode only; PaymentIntents land in a shared Stripe sandbox (no
# dashboard access). Replace inline if you want PaymentIntents to land in
# your own Stripe test account.
readonly STRIPE_KEY="pk_test_TYooMQauvdEDq54NiTphI7jx"

# @spree/cli looks for docker-compose.yml in the cwd, so all CLI calls
# happen from the backend dir.
cd "$BACKEND_DIR"

echo "==> Waiting for Spree to accept HTTP requests at $SPREE_URL/up"
for _ in $(seq 1 60); do
  if curl -fs "$SPREE_URL/up" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
if ! curl -fs "$SPREE_URL/up" >/dev/null 2>&1; then
  echo "Spree never came up. Check 'docker compose -f $BACKEND_DIR/docker-compose.yml logs web'." >&2
  exit 1
fi

echo "==> Seeding default Spree data (spree seed)"
npx @spree/cli seed

echo "==> Loading sample products and categories (spree sample-data)"
npx @spree/cli sample-data

echo "==> Creating publishable API key (spree api-key create)"
api_key_output=$(npx @spree/cli api-key create --name E2E --type publishable)

publishable_key=$(printf '%s\n' "$api_key_output" | grep -oE 'pk_[A-Za-z0-9_-]+' | head -n 1)
if [[ -z "$publishable_key" ]]; then
  echo "Could not extract publishable key from CLI output:" >&2
  printf '%s\n' "$api_key_output" >&2
  exit 1
fi

cat >"$ENV_FILE" <<EOF
# Generated by scripts/e2e/bootstrap-spree.sh — DO NOT EDIT
SPREE_API_URL=$SPREE_URL
SPREE_PUBLISHABLE_KEY=$publishable_key
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$STRIPE_KEY
EOF

echo
echo "==> Done. Wrote $ENV_FILE"
echo "    SPREE_API_URL=$SPREE_URL"
echo "    SPREE_PUBLISHABLE_KEY=${publishable_key:0:12}…"
