#!/usr/bin/env bash
# Bootstrap the E2E Spree backend using @spree/cli.
#
# Steps:
#   1. `spree seed` — seed the default store, roles, countries.
#   2. `spree sample-data` — load sample products, categories, images.
#   3. `spree api-key create --name E2E --type publishable` — mint a key
#      and capture the printed pk_… token.
#
# Idempotent: the CLI's seed/sample-data tasks are no-ops on already-seeded
# databases, and a fresh API key per run is fine (old "E2E" keys just
# accumulate but don't break anything).
#
# Output: writes `.env.e2e` at the repo root with SPREE_API_URL +
# SPREE_PUBLISHABLE_KEY for the storefront to consume.

set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
readonly BACKEND_DIR="$REPO_ROOT/e2e-backend"
readonly ENV_FILE="$REPO_ROOT/.env.e2e"
readonly SPREE_URL="http://localhost:4000"

# Stripe's public sample publishable key — same one used throughout
# https://docs.stripe.com/keys. Test-mode only; PaymentIntents land in a
# shared Stripe sandbox. Safe to commit.
readonly STRIPE_PUBLISHABLE_KEY="pk_test_TYooMQauvdEDq54NiTphI7jx"

# Stripe secret key. Must be a test-mode key (sk_test_…) paired with the
# publishable key above (or your own pair). Required by Spree to create
# PaymentIntents server-side during checkout.
#
# Not committed: GitHub's push protection flags any sk_test_ literal as a
# secret regardless of provenance. Export it before running this script:
#
#   export STRIPE_SECRET_KEY=sk_test_…
#   npm run e2e:up
#
# In CI, set it as a repository secret and inject via the workflow env.
# Stripe's documented public sample (see https://docs.stripe.com/keys)
# pairs with the pk_test_TYooMQauvdEDq54NiTphI7jx publishable key above.
if [[ -z "${STRIPE_SECRET_KEY:-}" ]]; then
  echo "STRIPE_SECRET_KEY is not set." >&2
  echo "Set it to a Stripe test-mode key (sk_test_…) and re-run." >&2
  echo "See script header for details." >&2
  exit 1
fi

if [[ "$STRIPE_SECRET_KEY" != sk_test_* ]]; then
  echo "STRIPE_SECRET_KEY must be a test-mode key (sk_test_…)." >&2
  echo "Got: ${STRIPE_SECRET_KEY:0:8}…" >&2
  exit 1
fi

# @spree/cli looks for docker-compose.yml in the cwd, so all CLI calls
# happen from the backend dir.
cd "$BACKEND_DIR"

echo "==> Waiting for Spree to accept HTTP requests at $SPREE_URL/up"
for _ in $(seq 1 60); do
  if curl -fs "$SPREE_URL/up" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done
if ! curl -fs "$SPREE_URL/up" >/dev/null 2>&1; then
  echo "Spree never came up. Check 'docker compose -f $BACKEND_DIR/docker-compose.yml logs web'." >&2
  exit 1
fi

echo "==> Seeding default Spree data (spree seed)"
npx @spree/cli seed

echo "==> Loading sample products and categories (spree sample-data)"
npx @spree/cli sample-data

# Vanilla Spree ships without any payment gateway configured. The Admin API
# can create one declaratively, but that endpoint only exists from Spree 5.5
# onward — this E2E targets the stable 5.4.3.1 image, so we fall back to a
# `bin/rails runner` snippet that creates a SpreeStripe::Gateway row directly.
# The script is idempotent: re-running on an already-created E2E gateway is
# a no-op (find_or_create_by on the unique name).
echo "==> Configuring Stripe payment gateway on the default store"
docker compose exec -T web bin/rails runner - <<RUBY
store = Spree::Store.default
gateway = Spree::PaymentMethod.where(type: 'SpreeStripe::Gateway', name: 'E2E Stripe').first_or_initialize
gateway.assign_attributes(
  active: true,
  display_on: 'both',
  auto_capture: true,
  stores: [store],
  preferences: {
    publishable_key: '$STRIPE_PUBLISHABLE_KEY',
    secret_key: '$STRIPE_SECRET_KEY'
  }
)
gateway.save!(validate: false)
puts "OK: gateway #{gateway.id} (#{gateway.name})"
RUBY

echo "==> Creating publishable API key (spree api-key create)"
api_key_output=$(npx @spree/cli api-key create --name E2E --type publishable)

publishable_key=$(printf '%s\n' "$api_key_output" | grep -oE 'pk_[A-Za-z0-9_-]+' | head -n 1)
if [[ -z "$publishable_key" ]]; then
  echo "Could not extract publishable key from CLI output:" >&2
  printf '%s\n' "$api_key_output" >&2
  exit 1
fi

cat >"$ENV_FILE" <<EOF
# Generated by scripts/e2e/bootstrap-spree.sh — DO NOT EDIT
SPREE_API_URL=$SPREE_URL
SPREE_PUBLISHABLE_KEY=$publishable_key
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
EOF

echo
echo "==> Done. Wrote $ENV_FILE"
echo "    SPREE_API_URL=$SPREE_URL"
echo "    SPREE_PUBLISHABLE_KEY=${publishable_key:0:12}…"
